### ISSUE TITLE
NSStringFromNRMAMeasurementType crash

### ISSUE THREAD

**Issue by asos-chrisblackmore** [newrelic/newrelic-ios-agent-spm#58]
## Description
Since upgrading to `7.5.0`, our customer facing app is seeing a crash relating to `NSStringFromNRMAMeasurementType`.

![Screenshot 2024-08-22 at 14 31 46](https://github.com/user-attachments/assets/899c7a5a-b955-4d35-9156-42edf67a9361)

We've been forced to pause our rollout since this crash is one of the highest in our app.

## Steps to Reproduce
Unknown

## Expected Behavior
The app to not crash.

**Comment by cdillard-NewRelic** [comment]
Please update to 7.5.1 where we fixed this. Thanks!

**Comment by asos-chrisblackmore** [comment]
@cdillard-NewRelic Great, thanks! Is it worth mentioning that in the release notes to visibility? I'd imagine we're not the only vendors experiencing this.

**Comment by asos-chrisblackmore** [comment]
@cdillard-NewRelic We've just upgraded and released a new version - the crash is still there but now with a different stack trace:
![Screenshot 2024-08-29 at 08 31 25](https://github.com/user-attachments/assets/a54df648-db69-4c8e-a0c7-c3deafb6be8e)

**Comment by cdillard-NewRelic** [comment]
Ah, thank you for reporting that. We've created a ticket locally to look into this NR_dispatch_once crash for our next release.

**Comment by smalsam-newr** [comment]
@asos-chrisblackmore Please post a full crash report for this issue when you are able, thank you.

**Comment by asos-chrisblackmore** [comment]
@smalsam-newr I'm redacting the codepath from the iOS app that this crash is stemming from, but there really isn't anything of note that you'd use from it, it's just the codepath from the codebase that is plugging into the New Relic SDK. There's 2 different stack traces that are recurring:

![Screenshot 2024-08-30 at 14 48 27](https://github.com/user-attachments/assets/a4f73c03-6f66-4e57-9575-1303263ee7ed)

![Screenshot 2024-08-30 at 14 49 53](https://github.com/user-attachments/assets/23e4c715-88b7-4867-8c66-6e60660ebe2e)

**Comment by apadmi-thomas** [comment]
We are also encountering the same problem in New Relic with 7.5.0
@smalsam-newr / @cdillard-NewRelic   can you confirm ETA for fix?

**Comment by cdillard-NewRelic** [comment]
Thank you for providing those crash stacks. We can confirm we have reproduced and fixed ex0 and ex2. This fixes will be included in our next release.  The other examples  (ex1, ex3, ex5) we will investigate the tickets which we've added to our JIRA system.  Please reach out to support and create a case containing more details. Thanks!

**Comment by apadmi-thomas** [comment]
> Thank you for providing those crash stacks. We can confirm we have reproduced and fixed ex0 and ex2. This fixes will be included in our next release. The other examples (ex1, ex3, ex5) we will investigate the tickets which we've added to our JIRA system. Please reach out to support and create a case containing more details. Thanks!

Ticket raised with crash logs.  Thanks!

**Comment by asos-callumtrounce** [comment]
Thanks so much @cdillard-NewRelic! Is there an ETA for the release that includes the crash fix?

**Comment by dhoerl** [comment]
WOW - two weeks and no response? My app is also crashing a lot. Rollback to some 7.4 release and wait?

**Comment by asos-callumtrounce** [comment]
Hi all, 

As an FYI we've updated the version of new relic to 7.5.2. 

Will let you know if that indeed solves the issue.

**Comment by asos-callumtrounce** [comment]
I'm happy to confirm that this has been resolved. The crash is no longer appearing.

**Comment by mbruin-NR** [comment]
Thank you for confirming that this crash is no longer appearing.
